OPT_DEFS += -DKEYCHRON_DIP_SWITCH_USER
OPT_DEFS += -UENABLE_FACTORY_TEST

OPT_DEFS += -DDYNAMIC_KEYMAP_LAYER_COUNT=6

#OPT_DEFS += -DDEBOUNCE=10
DEBOUNCE_TYPE = sym_defer_pk

JOYSTICK_ENABLE = yes
JOYSTICK_DRIVER = digital
OPT_DEFS += -DJOYSTICK_BUTTON_COUNT=5
OPT_DEFS += -DJOYSTICK_AXIS_COUNT=1
OPT_DEFS += -DJOYSTICK_AXIS_RESOLUTION=8

#VIA_ENABLE = yes

